### ISSUE TITLE
Web font on element with font-size:0 still shows text

### ISSUE THREAD

**Issue by mfn** [ariya/phantomjs#12173]
Using `phantomjs-1.9.7-linux-x86_64/bin/phantomjs`

From http://jsfiddle.net/j8pT9/ : 

``` html
You see me <span>you don't see me</span>
```

``` css
@font-face {
  font-family: 'Open Sans';
  src: url(http://themes.googleusercontent.com/static/fonts/opensans/v8/cJZKeOuBrn4kERxqtaUH3T8E0i7KZn-EPnyo3HZu7kw.woff) format('woff');
}
span {
  font-family: 'Open Sans';
  font-size:0px;
}
```

The text "you don't see me" is still shown, see http://i.imgur.com/GG7w7ZM.png .
If the element does not reference a web font, it works.
