### ISSUE TITLE
Issues with multiple webfonts

### ISSUE THREAD

**Issue by reinink** [ariya/phantomjs#12199]
I'm new to PhantomJS, and finding out that fonts are a bit of a challenge. SVG fonts work quite well:

``` css
@font-face {
    font-family: 'Font A';
    src: url('font_a.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Font B';
    src: url('font_b.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

The only problem with SVG fonts is that the text is not selectable in PDFs. The text selection issue doesn't exist when using the TIFF/WOFF formats, but I'm having issues with loading two fonts at a time.

This works:

``` css
@font-face {
    font-family: 'Font A';
    src: url('font_a.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
```

This does not (only one font is available):

``` css
@font-face {
    font-family: 'Font A';
    src: url('font_a.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Font B';
    src: url('font_b.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
```

What's odd is that the fonts that don't load actually don't revert to the default font, but rather are the custom font that does works. All custom fonts use just the one custom font that works.
