### ISSUE TITLE
phantomjs not rendering emoji characters correctly

### ISSUE THREAD

**Issue by sth519** [ariya/phantomjs#12461]
I'm trying to render a page that includes emoji characters into a PNG file.
However, the emoji characters (multibyte utf-8) are not displayed correctly.

![no-emoji](https://cloud.githubusercontent.com/assets/7388915/3941791/9989a878-2542-11e4-8d98-8ec178ed4e83.png)

I'm using phantomjs 1.9.7 (from homebrew) on OS X 10.9.
The page renders correctly in normal browsers.

**Comment by monkeycraps** [comment]
it display at web brow correctly, at mac os, with AppleColorEmoji
©😊(*^__^*) 嘻嘻……🐦🌰বাংলা bn হিলিয়ামΩ

but when render pdf, it dose't contain the emoji, i've install the ttf font , at my computer, set it by font-face

```css
@font-face {
    font-family: 'AppleColorEmoji';
    font-style: normal;
    font-weight: normal;
    src: url('font/emojione-apple.ttf');
}
body {
    font-family: 'FZCHYJW', 'fzltxh', 'AppleColorEmoji', 'Georgia', 'arial', 'sans-serif';
}

```

```html
<span>©😊(*^__^*) 嘻嘻……🐦🌰বাংলা bn হিলিয়ামΩ</span>
```
