### ISSUE TITLE
Maverick + Phantom 1.9.7, no fonts load

### ISSUE THREAD

**Issue by bourg-ismael** [ariya/phantomjs#12594]
Hi,

I have a problem with my webfonts on phantom.js 1.9.7. I run it on maverick.

My fonts :

``` css
@font-face
{
    font-family: "HelveticaNeue";
    src: url('../fonts/HelveticaNeue/HelveticaNeue.svg') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

I also tried with TTF and it's the same.

It renders this :
![capture d ecran 2014-09-23 a 10 54 16](https://cloud.githubusercontent.com/assets/6688384/4369624/3e35efd8-42ff-11e4-97f8-9c0842c68ca7.png)

Instead of this :
![capture d ecran 2014-09-23 a 10 54 07](https://cloud.githubusercontent.com/assets/6688384/4369625/3e3b99f6-42ff-11e4-9ff9-6f52b9854bda.png)
