### ISSUE TITLE
3D CSS Transforms not working

### ISSUE THREAD

**Issue by martinzaleski** [ariya/phantomjs#12779]
Hello!
When I try yo capture a page where CSS 3D Transforms are applied to certain elements, it doesn't look good. I think I've read PhantomJS does not support 3D Transforms yet.

Are you planning to support this feature or is there any workaround you could think of?

Thank you very much and keep up the good work!
Martin

**Comment by bogdancloud** [comment]
Any update on this issue?

**Comment by davidgorges** [comment]
There's currently no support for 3D CSS transformations as it's saying on ["Supported Web Standards"](http://phantomjs.org/supported-web-standards.html):
> _CSS 3-D_ needs a perspective-correct implementation of texture mapping. It can't be implemented without a penalty in performance.

But: 

> Each of the above feature may be supported in the future if the technical challenges associated with the implementations are solved. Until then, do not rely on those features.

**Comment by dcworldwide** [comment]
Any update on this? Trying to record an animation that uses 3d transforms.

**Comment by bmustata** [comment]
Currently this is not supported and maybe will be supported in the future.

**Comment by mbharathi4747** [comment]
Any update on this issue?

**Comment by zackw** [comment]
WebKit core does support 3D transforms, but it is not clear to me what we would have to do to make them available in PhantomJS; there is no obvious toggle at the Qt level.  And, like other 3D features (e.g. WebGL) activating the feature might suddenly cause the program to grow a dependency on a GPU.

PhantomJS core development is extremely manpower-limited. We are not likely to dig into this in the near future.  If one of you wants to figure out what needs doing and send us a pull request, that would be very helpful.

**Comment by fredericlam** [comment]
Hi everyone.

A simple trick that worked for me after seeing that 3D css transform does not work with phantomJS.
After googling for hours, I just needed a simple feature, which was a simple "translate":

- in my svg file, the property style="transform:translate(X,Y)" works in the browser, but does not if I want to catch a screenshot with phantomJS.
- simply turn it to an attribute, so : transform="translate(X,Y)" and phantomJS understand it.

It saved me from coding an alternative to it.

**Comment by miriti** [comment]
The solution that helped me:
Simply added `-webkit-transfrom` css property along with the `transform` property (with the same value) and it did the trick.

**Comment by kachkaev** [comment]
Quite surprised that this issue is still open after ≈ 2 years. No way to render leaflet map markers because of this :–(

**Comment by pouu69** [comment]
-webkit-transfrom  is working very welll thx

**Comment by bittlestudio** [comment]
Hello guys.
-webkit-transform works for translate, scale, rotate, but DOES NOT work for rotateY, which is rotating in 3D.
If you guys have any progress or workarounds with regards to this, please let me know.
I’ve been more than 2 years now without being able to solve this… :(

Thanks

**Comment by myst729** [comment]
Even `-webkit-` works, it's still buggy, especially with `transition`.

**Comment by Vitallium** [comment]
Could you please try again with 2.5 binary? Thanks!

**Comment by myst729** [comment]
Tried 2.5.0 beta, no luck.

I'm using nightwatch to run some e2e tests.

When a button is clicked, the element `div.menu` will be appended an extra class name `.menu-open`. A very typical side menu slides in from left.

```css
.menu {
  transform: translate(-200px, 0);
  transition: transform 1s ease;
}
.menu-open {
  transform: translate(0, 0);
}
```

In my test case I check whether `div.menu` is in viewport before and after clicked. This works fine in Chrome and Firefox but fails in Phantom. Like said, Phantom 2.1.1 needs `-webkit-` so I added it.

```css
.menu {
  -webkit-transform: translate(-200px, 0);
  transform: translate(-200px, 0);
  transition: -webkit-transform 1s ease;
  transition: transform 1s ease;
}
.menu-open {
  -webkit-transform: translate(0, 0);
  transform: translate(0, 0);
}
```

The class name is added correctly, but `getComputedStyle()` shows that transform from `.menu-open` is not actually applied, still fails.

Until I finally get to this trick:

```css
.menu {
  -webkit-transform: translate(-200px, 0);
  transform: translate(-200px, 0);
  transition: -webkit-transform 1s ease;
  transition: transform 1s ease;
}
.menu-open {
  -webkit-transform: translate(0, 0);
  transform: translate(0, 0);
  /* The following two lines are the trick */
  transition: -webkit-transform 1s ease;
  transition: transform 1s ease;
}
```

This works as expected in Phantom 2.1.1, but it's quite dirty. And it's obviously the right thing to write project like this just to fool the tests.
