### ISSUE TITLE
Bootstrap2 modal

### ISSUE THREAD

**Issue by RSol** [ariya/phantomjs#13108]
Good day.

Try to use tests in codeception with phantomjs.

Problem is Bootstrap 2 modals shown too hight (see screenshot).

![modal](https://cloud.githubusercontent.com/assets/535813/6843201/293baede-d3a9-11e4-9a1d-12249d106733.png)

Code:
```php
$I->click(\InteractPage::$videoButtonAdd);
$I->wait(10);
$I->see('YouTube');
```

So I have error.

When see in browsers - all ok.

What I can do?

**Comment by ariya** [comment]
Thank you for submitting this ticket!

This issue tracker primarily serves as the tool to report and track bugs, defects, and development tasks.
For general question, code review request, or other related discussion, please post it to either:

 * the official [PhantomJS users mailing-list](http://groups.google.com/group/phantomjs)
 * [Stack Overflow](http://stackoverflow.com/questions/tagged/phantomjs) (with `phantomjs` tag)

If you have not read it yet, please check also a few tips on [Effective Q&A](https://github.com/ariya/phantomjs/wiki/Support).

**Comment by RSol** [comment]
Thank you for your answer.

I found how to solve this problem. 

I your **acceptance.suite.yml** in **WebDriver** section add **window_size: maximize**
```
WebDriver:
            browser: phantomjs
            url: 'http://localhost/'
            port: 4445
            window_size: maximize
```
