### ISSUE TITLE
Wrong result of PDF contents by Windows custom text size configuration.

### ISSUE THREAD

**Issue by mysticatea** [ariya/phantomjs#14306]
If I'm using a custom font size, PhantomJS cannot generate correct PDF.

There is this problem on length of millimeters.

``` css
.bounding-box-of-A4 {
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    width: calc(210mm - 1px);
    height: calc(297mm - 1px);
    padding: 4px;
    box-sizing: border-box;
    border: 3px solid red;
}
```

In the custom font size is 100% (default) case, it generated [expected.pdf](https://github.com/mysticatea/phantomjs-problem/blob/master/expected.pdf). This is what I expected.
But in 125% case, it generated [wrong.pdf](https://github.com/mysticatea/phantomjs-problem/blob/master/wrong.pdf). This is too small.

I'd like to get a workaround.
e.g. Can I make zoom level from the current font size configuration of OS?

Thank you.

---
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   - 2.1.1
2. What steps will reproduce the problem?
   - https://github.com/mysticatea/phantomjs-problem
3. Which operating system are you using?
   - Windows 7
4. Did you use binary PhantomJS or did you compile it from source?
   - `npm install phantomjs-prebuilt`
5. Please provide any additional information below.
   - Maybe related: #13553, #12685
