### ISSUE TITLE
Some select input CSS is not applied

### ISSUE THREAD

**Issue by davidherse** [ariya/phantomjs#14472]
Phantomjs version 2.1.1
Mac 10.11.5
Binary PhantomJS

**Issue:**
When creating a select input with the following CSS:

``` css
.selectInput {
    width: 90px;
    height: 50px;
    display: block;
    background: #fff;
    border: 0 solid;
    font-size: 18px;
    border-radius: 3px;
    box-sizing: border-box;
}
```

Phantom does not apply the height or rounded corners styles.

Chrome example
<img width="169" alt="screen shot 2016-08-13 at 12 34 39 pm" src="https://cloud.githubusercontent.com/assets/3256309/17641037/1e4de684-6153-11e6-83be-dda421899da2.png">

PhantomJS example
<img width="153" alt="screen shot 2016-08-13 at 12 34 57 pm" src="https://cloud.githubusercontent.com/assets/3256309/17641036/1e4d22a8-6153-11e6-9fb7-9e7f297321cb.png">

**Comment by ricokahler** [comment]
PhantomJS 2.1.1 uses and older version of Webkit so the web standards are behind but you'll be glad to know that they are currently updating the the latest webkit :D

To use modern web standards today use [autoprefixer](https://autoprefixer.github.io/) with the browser query of `safari >= 4`

try this out
```css
.selectInput {
    width: 90px;
    height: 50px;
    display: block;
    background: #fff;
    border: 0 solid;
    font-size: 18px;
    -webkit-border-radius: 3px;
            border-radius: 3px;
    -webkit-box-sizing: border-box;
            box-sizing: border-box;
}
```
