### ISSUE TITLE
phantomjs issue with unicode(utf8) 

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#14482]
I'm trying to run a test using codeception. webdriver and phantomjs 2.11. 
I write the below line for my test which contains Farsi characters.

``` php
$I->see('کمپین بنری');
```

my test pass using php browser and fail using phantomjs. I commented that line and the test passed with phantomjs as well. so phantomjs doesn't support unicode.

> phantomjs.exe --webdriver=4444 --output-encoding=utf8

I find it on [Command-line Options](http://phantomjs.org/api/command-line.html)

Operating System: Windows 8

Suite configuration: 

``` yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://platform.xxxx-local.ir
            browser: phantomjs
        - \Helper\Acceptance
```
