### ISSUE TITLE
Font not found after update to v2.1.1

### ISSUE THREAD

**Issue by ValentinH** [ariya/phantomjs#14661]
1. Which version of PhantomJS are you using? 2.1.1

3. Which operating system are you using?
Kubuntu 14.04 or Ubuntu 14.04 (tested on two machines)

4. Did you use binary PhantomJS or did you compile it from source?
Binary

5. Please provide any additional information below.

I'm rendering a local html file and I'm using a custom font downloaded from Google Fonts (PT Sans Narrow) that I installed on my system in `/usr/share/fonts/truetype`. 

Then my font is loaded in CSS with:
```css
body {
  font-family: "PT Sans Narrow", "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 16px;
}
```

This was working fine in v1.9.8
