### ISSUE TITLE
Crash on CSS Property `-webkit-clip-path`

### ISSUE THREAD

**Issue by Martin-Pitt** [ariya/phantomjs#14660]
> 1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

2.1.1

> 2. What steps will reproduce the problem?

  1. Opened a page with `-webkit-clip-path`

> 3. Which operating system are you using?

macOS 10.11.6

> 4. Did you use binary PhantomJS or did you compile it from source?

Binary PhantomJS, once from phantomjs site direct download and another via prebuilt NPM module.

> 5. Please provide any additional information below.

Narrowed down a crash to opening a page with `-webkit-clip-path` CSS property.

I had the following inside a <style> tag on the HTML page that was being loaded:

```css
#summary {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	-webkit-clip-path: polygon(66.66% 0%, 66.66% 0%, 33.33% 100%, 33.33% 100%);
	-webkit-transition: -webkit-clip-path 0.5s ease-in-out;
}
```
