### ISSUE TITLE
PhantomJs 2.1.1- Unable to Switch to Iframe with executeInSelenium function (as there is no name for my iframe) and this is resulting my test case fail when I ran using phantom #3848

### ISSUE THREAD

**Issue by rajabhaskar** [ariya/phantomjs#14708]
#### I have a vimeo video frame on my webpage. Trying to switch to Iframe in PhantomJs 2.1.1 which is failing to access the elements inside it, whereas I am able get this TC working in Chrome and Firefox with the same code.

As per ticket [#3848](https://github.com/Codeception/Codeception/issues/3848), codeception team confirmed that it's not an issue from Codeception 
```js
$this->executeInSelenium(function (Facebook\WebDriver\Remote\RemoteWebDriver $webDriver)use ($video_iframe, $locatorType){
$webDriver->switchTo()->frame($webDriver->findElement(WebDriverBy::$locatorType($video_iframe)));
});

$this->click(".hd"); // .hd is the css locator for video quality adjuster button on play progress bar. 
```
####

> **Console Ouput:**
```
 CSS or XPath element with '.hd' was not found

1) Landing.feature: i am on /landing
 Test  src/xxxxxxx/Tests\acceptance\Landing.feature:i am on /landing
 Step  Move mouse over ".hd"
 Fail  CSS or XPath element with '.hd' was not found.

Scenario Steps:

 22. $I->moveMouseOver(".hd")
 21. $I->getLocator("common","vimeo_playing_button")
 20. $I->getLocator("common","vimeo_video_quality_button")
 19. $I->executeInSelenium("Closure") // here we have the switch to ifram code

```

```bash
# paste output here
```
I get locator "landing","landing_page_video"
   I get test data "landing_page_te...","landing_video_p..."
   I get locator "landing","landing_page_video"
   I click ".evy_lndg_video>iframe"
   I execute in selenium "Closure"
   I get locator "landing","landing_page_video"
   I execute in selenium "Closure"
   I get locator "common","vimeo_video_quality_button"
   I get locator "common","vimeo_playing_button"
   I move mouse over ".hd"

  [Selenium browser Logs]  EMPTY
 FAIL
 Fail  CSS or XPath element with '.hd' was not found.

### Details

* Codeception version: 2.2.1
* PHP Version:7.0.7
* PhantomJs Version: 2.1.1

```yml
modules:
    enabled:
        - WebDriver

config:
        WebDriver:
            url: 'https://xxx.yyyyy.com'
            browser: phantomjs
            wait: 2
            window_size: maximize
            clear_cookies: false
            capabilities:
                  unexpectedAlertBehaviour: 'accept'
                  handlesAlerts: true
```
